dist: trusty
sudo: false
language: rust
cache:
  directories:
    - $HOME/.cache/
    - $HOME/.cargo/
    - $TRAVIS_BUILD_DIR/target

before_cache:
  - find $TRAVIS_BUILD_DIR/target/debug -maxdepth 1 -type f -delete

matrix:
  include:
    - os: linux
      rust: nightly-2017-05-29
      env: COMPILER=g++-4.8 RUSTFMT_VERSION=v0.6.0 CXX=g++-4.8
      addons:
         apt:
            sources: ['ubuntu-toolchain-r-test']
            packages: ['g++-4.8', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libdw-dev', 'libelf-dev', 'elfutils', 'binutils-dev']
    - os: osx
      rust: nightly-2017-05-29
      env: COMPILER=clang++ SKIP_FORMAT_CHECK=true CXX=clang++

install:
  - export LOCAL_DIR=$HOME/.cache/
  - export PATH=$PATH:$LOCAL_DIR/bin:$HOME/.cargo/bin
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$LOCAL_DIR/lib
  - export LIBRARY_PATH=${LIBRARY_PATH}:$LOCAL_DIR/lib
  - export DYLD_LIBRARY_PATH=${DY_LIBRARY_PATH}:$LOCAL_DIR/lib
  - export CXXFLAGS=-I$LOCAL_DIR/include
  - travis_wait make -f travis-build/Makefile prepare_${TRAVIS_OS_NAME}

script:
  - make -f travis-build/Makefile test_${TRAVIS_OS_NAME}

after_success:
  # TODO add following into build progress after failed cases are resolved.
  - make -f travis-build/Makefile cover_${TRAVIS_OS_NAME}
