[package]
name = "tikv"
version = "0.0.1"
keywords = ["KV", "distributed-systems", "raft"]
build = "build.rs"

[build-dependencies]
time = "0.1"

[features]
default = []
dev = ["clippy", "mem-profiling"]
static-link = ["rocksdb/static-link"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]
mem-profiling = ["jemallocator"]

[lib]
name = "tikv"

[[bin]]
name = "tikv-server"

[[bin]]
name = "bench-tikv"
path = "benches/bin/bench-tikv.rs"

[[bin]]
name = "tikv-ctl"

[[test]]
name = "tests"

[dependencies]
log = "0.3"
byteorder = "0.5"
rand = "0.3"
quick-error = "0.2"
tempdir = "0.3"
uuid = { version = "0.3", features = ["v4"] }
time = "0.1"
threadpool = "1.0.0"
toml = "0.1"
num = "0.1"
libc = "0.2"
crc = "1.2"
fs2 = "0.4"
clippy = {version = "*", optional = true}
rustc-serialize = "0.3"
protobuf = "1.2.1"
nix = "0.6.0"
utime = "0.1"
chrono = "0.2"
lazy_static = "0.2.1"
backtrace = "0.2.3"
clap = "2"
url = "1.2"
regex = "0.1"
fnv = "1.0"
sys-info = "0.4.1"
ordermap = "0.2"
flat_map = "0.0.4"
mio = "0.5"
futures = "0.1"
futures-cpupool = "0.1.5"
tokio-core = "0.1"
tokio-timer = "0.1"

[target.'cfg(unix)'.dependencies]
signal = "0.2"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"
branch = "busyjay/grpc-dev"

[dependencies.tipb]
git = "https://github.com/pingcap/tipb.git"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
default-features = false
features = ["nightly", "push", "process"]

[dependencies.grpc]
git = "https://github.com/pingcap/grpc-rs.git"
branch = "busyjay/dev"
features = ["static-link"]

[dependencies.jemallocator]
git = "https://github.com/busyjay/jemallocator.git"
branch = "dev"
features = ["profiling"]
optional = true

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
codegen-units = 2

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 3
debug = true
